services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-viio-db
    ports:
      - 3310:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ./mysql-data:/var/lib/mysql

  api-backend:
    depends_on:
      - mysql-db
    build:
      context: .
      target: ${STAGE}
      dockerfile: Dockerfile
    container_name: next-api-backend
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
